### ISSUE TITLE
Tasks for Milestone 1

### ISSUE THREAD

**Issue by LisaSeq** [UBC-MDS/DSCI_525_Group_8#1]
1. Teamwork contract
- [ ] Created and to be reviewed (ALL) 
2. Create project repo and shared files
- [ ] Project summary in README (@marianagyby )
- [ ] Everyone is to make their own local notebook (not pushed to GitHub) to work through parts 3-4 and run the timing experiments on their local machines. (ALL)
- [ ] We have created a milestone_1.ipynb in the notebooks folder, where we will compile our work and submit as the final copy for this milestone. 
3. Download data & Combine CSV's
- [ ] We all need to do this in our local notebooks, and one copy of the code will be added to final notebook (All)
- [ ] Each member needs to report the runtime on their local machine (ALL)
4. Load combined CSV and perform simple EDA
- [ ] Two approaches to reduce memory usage and what we will do for EDA. Each of us needs to do the same steps in our local notebooks and report the EDA runtimes (ALL)
7. Transfer df from python to R and perform EDA in R
- [ ] Choose method to transfer df from python to R and explain why (TBD)
- [ ] Perform simple EDA in R (@LisaSeq )
8. Other
- [ ] Add discussion of challenges we faced when dealing with large data in milestone_1.ipynb notebook (ALL)
- [ ] Review & Submission (@marianagyby )
